package com.zhuyun.jingxi.android;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.zhuyun.jingxi.android.FriendsEntity;
import com.zhuyun.jingxi.android.HomeListEntity;
import com.zhuyun.jingxi.android.GiftRecommentEntity;
import com.zhuyun.jingxi.android.GiftClassifyEntity;
import com.zhuyun.jingxi.android.GiftStrategyEntity;

import com.zhuyun.jingxi.android.FriendsEntityDao;
import com.zhuyun.jingxi.android.HomeListEntityDao;
import com.zhuyun.jingxi.android.GiftRecommentEntityDao;
import com.zhuyun.jingxi.android.GiftClassifyEntityDao;
import com.zhuyun.jingxi.android.GiftStrategyEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig friendsEntityDaoConfig;
    private final DaoConfig homeListEntityDaoConfig;
    private final DaoConfig giftRecommentEntityDaoConfig;
    private final DaoConfig giftClassifyEntityDaoConfig;
    private final DaoConfig giftStrategyEntityDaoConfig;

    private final FriendsEntityDao friendsEntityDao;
    private final HomeListEntityDao homeListEntityDao;
    private final GiftRecommentEntityDao giftRecommentEntityDao;
    private final GiftClassifyEntityDao giftClassifyEntityDao;
    private final GiftStrategyEntityDao giftStrategyEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        friendsEntityDaoConfig = daoConfigMap.get(FriendsEntityDao.class).clone();
        friendsEntityDaoConfig.initIdentityScope(type);

        homeListEntityDaoConfig = daoConfigMap.get(HomeListEntityDao.class).clone();
        homeListEntityDaoConfig.initIdentityScope(type);

        giftRecommentEntityDaoConfig = daoConfigMap.get(GiftRecommentEntityDao.class).clone();
        giftRecommentEntityDaoConfig.initIdentityScope(type);

        giftClassifyEntityDaoConfig = daoConfigMap.get(GiftClassifyEntityDao.class).clone();
        giftClassifyEntityDaoConfig.initIdentityScope(type);

        giftStrategyEntityDaoConfig = daoConfigMap.get(GiftStrategyEntityDao.class).clone();
        giftStrategyEntityDaoConfig.initIdentityScope(type);

        friendsEntityDao = new FriendsEntityDao(friendsEntityDaoConfig, this);
        homeListEntityDao = new HomeListEntityDao(homeListEntityDaoConfig, this);
        giftRecommentEntityDao = new GiftRecommentEntityDao(giftRecommentEntityDaoConfig, this);
        giftClassifyEntityDao = new GiftClassifyEntityDao(giftClassifyEntityDaoConfig, this);
        giftStrategyEntityDao = new GiftStrategyEntityDao(giftStrategyEntityDaoConfig, this);

        registerDao(FriendsEntity.class, friendsEntityDao);
        registerDao(HomeListEntity.class, homeListEntityDao);
        registerDao(GiftRecommentEntity.class, giftRecommentEntityDao);
        registerDao(GiftClassifyEntity.class, giftClassifyEntityDao);
        registerDao(GiftStrategyEntity.class, giftStrategyEntityDao);
    }
    
    public void clear() {
        friendsEntityDaoConfig.getIdentityScope().clear();
        homeListEntityDaoConfig.getIdentityScope().clear();
        giftRecommentEntityDaoConfig.getIdentityScope().clear();
        giftClassifyEntityDaoConfig.getIdentityScope().clear();
        giftStrategyEntityDaoConfig.getIdentityScope().clear();
    }

    public FriendsEntityDao getFriendsEntityDao() {
        return friendsEntityDao;
    }

    public HomeListEntityDao getHomeListEntityDao() {
        return homeListEntityDao;
    }

    public GiftRecommentEntityDao getGiftRecommentEntityDao() {
        return giftRecommentEntityDao;
    }

    public GiftClassifyEntityDao getGiftClassifyEntityDao() {
        return giftClassifyEntityDao;
    }

    public GiftStrategyEntityDao getGiftStrategyEntityDao() {
        return giftStrategyEntityDao;
    }

}
