package com.zhuyun.jingxi.android;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table GIFT_CLASSIFY_ENTITY.
 */
public class GiftClassifyEntity {

    private Long id;
    private Long classiftyId;
    private String name;
    private String imgIconUrl;

    public GiftClassifyEntity() {
    }

    public GiftClassifyEntity(Long id) {
        this.id = id;
    }

    public GiftClassifyEntity(Long id, Long classiftyId, String name, String imgIconUrl) {
        this.id = id;
        this.classiftyId = classiftyId;
        this.name = name;
        this.imgIconUrl = imgIconUrl;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getClassiftyId() {
        return classiftyId;
    }

    public void setClassiftyId(Long classiftyId) {
        this.classiftyId = classiftyId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getImgIconUrl() {
        return imgIconUrl;
    }

    public void setImgIconUrl(String imgIconUrl) {
        this.imgIconUrl = imgIconUrl;
    }

}
