package com.zhuyun.jingxi.android;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.zhuyun.jingxi.android.GiftStrategyEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table GIFT_STRATEGY_ENTITY.
*/
public class GiftStrategyEntityDao extends AbstractDao<GiftStrategyEntity, Long> {

    public static final String TABLENAME = "GIFT_STRATEGY_ENTITY";

    /**
     * Properties of entity GiftStrategyEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property StrategyId = new Property(1, Long.class, "strategyId", false, "STRATEGY_ID");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property ImgIconUrl = new Property(3, String.class, "imgIconUrl", false, "IMG_ICON_URL");
        public final static Property WishCount = new Property(4, Integer.class, "wishCount", false, "WISH_COUNT");
        public final static Property Sort = new Property(5, Integer.class, "sort", false, "SORT");
    };


    public GiftStrategyEntityDao(DaoConfig config) {
        super(config);
    }
    
    public GiftStrategyEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'GIFT_STRATEGY_ENTITY' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'STRATEGY_ID' INTEGER," + // 1: strategyId
                "'NAME' TEXT," + // 2: name
                "'IMG_ICON_URL' TEXT," + // 3: imgIconUrl
                "'WISH_COUNT' INTEGER," + // 4: wishCount
                "'SORT' INTEGER);"); // 5: sort
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'GIFT_STRATEGY_ENTITY'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, GiftStrategyEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long strategyId = entity.getStrategyId();
        if (strategyId != null) {
            stmt.bindLong(2, strategyId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String imgIconUrl = entity.getImgIconUrl();
        if (imgIconUrl != null) {
            stmt.bindString(4, imgIconUrl);
        }
 
        Integer wishCount = entity.getWishCount();
        if (wishCount != null) {
            stmt.bindLong(5, wishCount);
        }
 
        Integer sort = entity.getSort();
        if (sort != null) {
            stmt.bindLong(6, sort);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public GiftStrategyEntity readEntity(Cursor cursor, int offset) {
        GiftStrategyEntity entity = new GiftStrategyEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // strategyId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // imgIconUrl
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // wishCount
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5) // sort
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, GiftStrategyEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setStrategyId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setImgIconUrl(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setWishCount(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setSort(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(GiftStrategyEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(GiftStrategyEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
