package com.zhuyun.jingxi.android;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table HOME_LIST_ENTITY.
 */
public class HomeListEntity {

    private Long id;
    private Long wishId;
    private String nickName;
    private String portraitUrl;
    private Integer gender;
    private Long utpTime;
    private String content;
    private String imgUrl;
    private String goodsName;
    private Integer type;
    private Double cfPrice;
    private Integer likeNum;
    private Integer commNum;
    private Integer isFriend;
    private Long wishUserId;
    private Integer isLiked;

    public HomeListEntity() {
    }

    public HomeListEntity(Long id) {
        this.id = id;
    }

    public HomeListEntity(Long id, Long wishId, String nickName, String portraitUrl, Integer gender, Long utpTime, String content, String imgUrl, String goodsName, Integer type, Double cfPrice, Integer likeNum, Integer commNum, Integer isFriend, Long wishUserId, Integer isLiked) {
        this.id = id;
        this.wishId = wishId;
        this.nickName = nickName;
        this.portraitUrl = portraitUrl;
        this.gender = gender;
        this.utpTime = utpTime;
        this.content = content;
        this.imgUrl = imgUrl;
        this.goodsName = goodsName;
        this.type = type;
        this.cfPrice = cfPrice;
        this.likeNum = likeNum;
        this.commNum = commNum;
        this.isFriend = isFriend;
        this.wishUserId = wishUserId;
        this.isLiked = isLiked;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getWishId() {
        return wishId;
    }

    public void setWishId(Long wishId) {
        this.wishId = wishId;
    }

    public String getNickName() {
        return nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    public String getPortraitUrl() {
        return portraitUrl;
    }

    public void setPortraitUrl(String portraitUrl) {
        this.portraitUrl = portraitUrl;
    }

    public Integer getGender() {
        return gender;
    }

    public void setGender(Integer gender) {
        this.gender = gender;
    }

    public Long getUtpTime() {
        return utpTime;
    }

    public void setUtpTime(Long utpTime) {
        this.utpTime = utpTime;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getImgUrl() {
        return imgUrl;
    }

    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    public String getGoodsName() {
        return goodsName;
    }

    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Double getCfPrice() {
        return cfPrice;
    }

    public void setCfPrice(Double cfPrice) {
        this.cfPrice = cfPrice;
    }

    public Integer getLikeNum() {
        return likeNum;
    }

    public void setLikeNum(Integer likeNum) {
        this.likeNum = likeNum;
    }

    public Integer getCommNum() {
        return commNum;
    }

    public void setCommNum(Integer commNum) {
        this.commNum = commNum;
    }

    public Integer getIsFriend() {
        return isFriend;
    }

    public void setIsFriend(Integer isFriend) {
        this.isFriend = isFriend;
    }

    public Long getWishUserId() {
        return wishUserId;
    }

    public void setWishUserId(Long wishUserId) {
        this.wishUserId = wishUserId;
    }

    public Integer getIsLiked() {
        return isLiked;
    }

    public void setIsLiked(Integer isLiked) {
        this.isLiked = isLiked;
    }

}
